name: "binaries"

on: [push]

jobs:
  linux: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Show GCC
      run: gcc -v

    - name: Setup Lua
      run: |
        curl -O https://www.lua.org/ftp/lua-5.4.6.tar.gz
        tar -xzf lua-5.4.6.tar.gz
        cd lua-5.4.6; make

    - name: Get LPeg
      run: |
        curl -o lpeg.tar.gz https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz
        tar -xzf lpeg.tar.gz

    - name: Get Luafilesystem
      run: |
        curl -L -o luafilesystem.tar.gz https://github.com/keplerproject/luafilesystem/archive/v1_8_0.tar.gz
        tar -xzf luafilesystem.tar.gz

    - name: Build
      run: gcc -o moon '-Ilua-5.4.6/src/' bin/binaries/moon.c lpeg-1.1.0/lpvm.c lpeg-1.1.0/lpcap.c lpeg-1.1.0/lptree.c lpeg-1.1.0/lpcode.c lpeg-1.1.0/lpprint.c


  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - uses: msys2/setup-msys2@v2
      with:
        install: gcc make curl

    - name: Show GCC
      run: gcc -v

    - name: Setup Lua
      run: |
        curl -O https://www.lua.org/ftp/lua-5.4.6.tar.gz
        tar -xzf lua-5.4.6.tar.gz
        cd lua-5.4.6; make PLAT=mingw

    - name: Get LPeg
      run: |
        curl -o lpeg.tar.gz https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz
        tar -xzf lpeg.tar.gz

    - name: Get Luafilesystem
      run: |
        curl -L -o luafilesystem.tar.gz https://github.com/keplerproject/luafilesystem/archive/v1_8_0.tar.gz
        tar -xzf luafilesystem.tar.gz

    - name: List Files
      run: Get-ChildItem -Recurse

    - name: Run Lua
      run: lua-5.4.6/src/lua.exe -v

    - name: Build
      run: gcc -o moon.exe '-Ilua-5.4.6/src/' bin/binaries/moon.c lpeg-1.1.0/lpvm.c lpeg-1.1.0/lpcap.c lpeg-1.1.0/lptree.c lpeg-1.1.0/lpcode.c lpeg-1.1.0/lpprint.c




